apiVersion: v1
kind: ServiceAccount
metadata:
  name: cache-initializer-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cache-initializer-role
rules:
  - apiGroups: ["*"]
    resources:
      - leaderworksets
      - services
      - serviceaccounts
    verbs: ["create", "get", "list", "watch"]
  - apiGroups: [ "*" ]
    resources:
      - trainjobs
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cache-initializer-role-binding
roleRef:
  name: cache-initializer-role
  kind: ClusterRole
subjects:
  - kind: ServiceAccount
    name: cache-initializer-sa
    namespace: cache-test
---
apiVersion: trainer.kubeflow.org/v1alpha1
kind: ClusterTrainingRuntime
metadata:
  name: torch-distributed-with-cache
spec:
  mlPolicy:
    numNodes: 1
    torch:
      numProcPerNode: auto
  template:
    spec:
      replicatedJobs:
      - name: dataset-initializer
        replicas: 1
        template:
          metadata:
            labels:
              trainer.kubeflow.org/trainjob-ancestor-step: dataset-initializer
          spec:
            template:
              spec:
                serviceAccountName: cache-initializer-sa
                containers:
                  - name: dataset-initializer
                    image: docker.apple.com/achitneni/cache_initializer:0c8441d7
                    env:
                      - name: IMAGE
                        value: "docker.apple.com/achitneni/arrow_cache:b59025d"
      - name: node
        dependsOn:
          - name: dataset-initializer
            status: Complete
        template:
          metadata:
            labels:
              trainer.kubeflow.org/trainjob-ancestor-step: trainer
          spec:
            template:
              spec:
                containers:
                  - name: node
                    image: pytorch/pytorch:2.5.0-cuda12.4-cudnn9-runtime
                    command:
                      - /bin/bash
                      - -c
                      - |
                        echo "Torch Distributed Runtime"

                        echo "--------------------------------------"
                        echo "Torch Default Runtime Env"
                        env | grep PET_

                        pip list
