apiVersion: v1
kind: ServiceAccount
metadata:
  name: $NAME-sa
  annotations:
    eks.amazonaws.com/sts-regional-endpoints: "true"
    eks.amazonaws.com/role-arn: $IAM_ROLE
---
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: $NAME
spec:
  replicas: 1
  leaderWorkerTemplate:
    size: $SIZE
    leaderTemplate:
      metadata:
        labels:
          app: $NAME-head
      spec:
        serviceAccountName: $NAME-sa
        containers:
        - name: head
          image: $IMAGE
          command: [ "head" ]
          args:
            - "0.0.0.0"
            - "50051"
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
          env:
            - name: RUNTIME_ENV
              value: "CLOUD"
          ports:
            - containerPort: 50051
    workerTemplate:
      spec:
        serviceAccountName: $NAME-sa
        containers:
        - name: worker
          image: $IMAGE
          command: ["worker"]
          args:
            - "0.0.0.0"
            - "50051"
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "2"
              memory: "2Gi"
          ports:
          - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: $NAME-service
spec:
  selector:
    app: $NAME-head
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
